(in-package :midi-packetiser)
(defun tester()
  (let ((fd (iolib.syscalls:open "/dev/ttyS2" o-rdwr))
	(midi-speed 31250)
	(test-data '(144 35 111)))
    (unwind-protect (cffi:with-foreign-pointer (tio (cffi:foreign-type-size '(:struct termios2)))
		      (assert (>= (iolib.syscalls:ioctl fd tcgets2 tio)
				  0))
		      (cffi:with-foreign-slots ((c-cflag c-ispeed c-ospeed) tio
						termios2)
			(setf c-cflag (logior bother
					      (logand (lognot cbaud)
						      c-cflag)))
			(setf c-ispeed midi-speed)
			(print (list c-cflag c-ispeed c-ospeed))
			(cffi:with-foreign-object (foo :uchar 3)
			  (dotimes (i 3)
			    (setf (cffi:mem-aref foo :uchar i)
				  (nth i test-data)))
			  (loop (sleep 0.5)
			     (iolib.syscalls:write fd foo 3)))))
      (iolib.syscalls:close fd))))
